#38 docs: CONTRIBUTING.md
Qithub-BOT/QiiCipher pull request #46
Opened 2021-06-04 06:03 UTC by KEINOS

Issue #38 のドラフト PR 〜

## 含める内容

- [ ] Issue, Discussions の棲み分け
- [ ] 何かに手をつけている場合は、内容が重ならないように Draft PR で実装前に作業ブランチを PR すること
    - 添付画像 URL: `https://user-images.githubusercontent.com/11840938/120753083-99484e00-c545-11eb-836a-afafa9bee29a.png`<br> <kbd>![](https://user-images.githubusercontent.com/11840938/120753083-99484e00-c545-11eb-836a-afafa9bee29a.png)</kbd>
    - [ ] レビューのタイミング
- [ ] `shfmt` `shellcheck` `shellspec` によるテストがあること
    - [ ] テストの実行方法
    - [ ] VSCode + Docker ユーザの場合は Remote-Containers に対応していること
- [ ] 現在は Bash だが、なるべく POSIX 準拠で実装して欲しいこと
- [ ] 基本的なテストの書き方

2021-06-10 04:51 UTC, KEINOS commented
「テストの書き方」は断念しました。

他も、あまりコネくり回してもアレなので、とりあえず一旦 PR してしまいます。

お手すきにご確認お願いしまーす！

2021-06-10 15:14 UTC, yoshi389111 requested changes
大作ですね。 お疲れ様です。 🎉 

いくつか気になるところがありました。
お手数ですが、ご確認願います。

2021-06-10 15:14 UTC, yoshi389111 commented on .github/HOW_TO_RUN_TESTS.md
> +- 【注意 2】GitHub の無料実行枠を消費します。ローカルで実行するか、[Draft PR](./.github/HOW_TO_PULL_REQUEST.md#draft-pr-%E3%81%AE%E3%82%B9%E3%82%B9%E3%83%A1) してしまうことをオススメします。
パブリックリポジトリの場合には、無料ではないでしょうか？

* [About billing for GitHub Actions](https://docs.github.com/ja/billing/managing-billing-for-github-actions/about-billing-for-github-actions)

2021-06-11 08:20 UTC, KEINOS commented on .github/HOW_TO_RUN_TESTS.md
> +- 【注意 2】GitHub の無料実行枠を消費します。ローカルで実行するか、[Draft PR](./.github/HOW_TO_PULL_REQUEST.md#draft-pr-%E3%81%AE%E3%82%B9%E3%82%B9%E3%83%A1) してしまうことをオススメします。
ほんとだ ... 以前パブリックなのに制限を受けた気がしたのですが、どうやら API のリクエスト制限と勘違いしていたようです！

2021-06-11 08:25 UTC, KEINOS commented on .github/HOW_TO_PULL_REQUEST.md
> +レビュアーの `Approved` が付くと、リポジトリ責任者（不在の場合はメンテナ）の判断により PR が `main` ブランチにマージ（`squash merge`）されます。 （`squash` に関しては下部にある「理想的な PR の流れ」をご覧ください）
これも `master` です！

2021-06-11 08:28 UTC, KEINOS commented on README.md
> +    - 設置する際に**コマンドに実行権限を与えるのを忘れない**でください。（例：`chmod 0744 ./enc`）
oh ... これじゃ実行して紅は 🙅  ジャン！ X JAPAN！

2021-06-11 08:30 UTC, KEINOS commented on README.md
> +  - `openssl`: 別途 [OpenSSL](https://ja.wikipedia.org/wiki/OpenSSL) のコマンドのインストールが必要です。
そうだ！`OpenSSH` が必ず入っているというわけではないですものね。修正しました！

2021-06-11 08:31 UTC, KEINOS commented on CONTRIBUTING.md
> +- [コントリビュータ一覧](https://docs.github.com/ja/github/getting-started-with-github/quickstart/github-glossary#contributor) | QiiCipher @ GitHub
🦊 🐦 🐷  一覧のリンク、双方修正しました！

2021-06-11 09:34 UTC, KEINOS commented on .github/HOW_TO_PULL_REQUEST.md
> +レビュアーの `Approved` が付くと、リポジトリ責任者（不在の場合はメンテナ）の判断により PR が `main` ブランチにマージ（`squash merge`）されます。 （`squash` に関しては下部にある「理想的な PR の流れ」をご覧ください）
修正しました！

2021-06-11 09:34 UTC, KEINOS commented on .github/HOW_TO_RUN_TESTS.md
> +- 【注意 2】GitHub の無料実行枠を消費します。ローカルで実行するか、[Draft PR](./.github/HOW_TO_PULL_REQUEST.md#draft-pr-%E3%81%AE%E3%82%B9%E3%82%B9%E3%83%A1) してしまうことをオススメします。
修正しました！

2021-06-11 14:22 UTC, yoshi389111 approved these changes

2021-06-11 14:22 UTC, yoshi389111 commented
問題ありません！

![LGTM](https://github.com/yoshi389111/yoshi389111/raw/main/LGTM/LGTM_sushi.png)

2021-06-11 23:40 UTC, merged