Change random to openssl
Qithub-BOT/QiiCipher pull request #53
Opened 2021-06-09 14:05 UTC by yoshi389111

## 関連

* issue #49 [POSIX準拠] $RANDOM を OpenSSL で代替
* discussions #39 非POSIXコマンドの書き換え案

## 対応内容

* `$RANDOM` を `openssl rand` に変更 #49
* 不要な md5 ラッパー関数の削除
* テスト `[[ ～ ]]` を `[ ～ ]` に変更
* シェルを bash から sh に変更
* `$BASH_SOURCE` を `$0` に変更

## やっていないこと

* `md5` / `md5sum` を `openssl dgst` に置き換え
* openssl のインストールチェック #33 #23

2021-06-10 00:32 UTC, KEINOS commented
> シェルを bash から sh に変更

![シェー_sh](https://user-images.githubusercontent.com/11840938/121446579-c5911e00-c9ce-11eb-9c76-28267b139308.gif)

2021-06-10 02:56 UTC, KEINOS requested changes
`getRandStr` 内の `exit` の件は無視していただいて、クォートだけお願いします。

2021-06-10 02:56 UTC, KEINOS commented on bin/archive
>  }
あー、`getRandStr` の結果を変数に代入する際にチェックしているから、大丈夫か。

2021-06-10 02:56 UTC, KEINOS commented on bin/check
> +FILENAME=${SAMPLETEXT}
```diff
- FILENAME=${SAMPLETEXT}
+ FILENAME="${SAMPLETEXT}"
```

2021-06-10 14:12 UTC, yoshi389111 commented on bin/archive
> +if ! PASSWORD=$(getRandStr); then
修正しました（類似含め）

2021-06-10 14:12 UTC, yoshi389111 commented on bin/check
> +FILENAME=${SAMPLETEXT}
修正しました

2021-06-10 14:35 UTC, yoshi389111 commented on bin/archive
>  }
一応簡単に思いを書いておきます。

受け取るときに `SAMPLETEXT="$(getRandStr)"` のようにしていると、 `getRandStr()` の中で `exit` しても終了しないようです。

```shell-session
$ cat a.sh
#!/usr/bin/sh

getRandStr() {
    echo "error"
    exit 1
}

result=$(getRandStr)
echo "hoge"
$ ./a.sh
hoge
```

そのため、呼び出し元でエラー判定が必須になります。

また、`openssl rand -hex 16` だけでも、終了コードは返ってくるようです。

なので、対応は2種類考えられます。

一つは、現在のソースの通り、`getRandStr()` では何もせず、呼び出し元でチェックする。
この場合には、トータル行数が少な目になります。

```shell
getRandStr() {
    openssl rand -hex 16 2>&1
}

if ! SAMPLETEXT="$(getRandStr)"; then
    echo >&2 'OpenSSL によるランダム値の取得に失敗しました。'
    echo >&2 "エラー内容: ${SAMPLETEXT}"
    exit 1
fi
```

もう一つは、`getRandStr()` でチェックして、エラーを出力。
呼び出し元でもチェックする（エラー出力はしない）。
将来、 `getRandStr()` を共通化する時には、こちらの方が良いかもしれません。

```shell
getRandStr() {
    rand=$(openssl rand -hex 16 2>&1) || {
        echo >&2 'OpenSSL によるランダム値の取得に失敗しました。'
        echo >&2 "エラー内容: ${rand}"
        return 1
    }
    echo "$rand"
}

if ! SAMPLETEXT="$(getRandStr)"; then
    exit 1
fi
```

今のうちの後者の書き方にしたほうが良いだろうという判断であれば、もちろん直すのはやぶさかではありません。

2021-06-11 07:41 UTC, KEINOS approved these changes
![merge_it_before_changes](https://user-images.githubusercontent.com/11840938/121649743-d5465a80-cad3-11eb-8997-97fd398d79d4.jpeg)

2021-06-11 07:41 UTC, KEINOS commented on bin/archive
>  }
そうか、サブシェルで実行されるわけですものね。`exit` は効かないっすね。`return` が良いとは思いますが、汎用関数を外部ファイル化する時にでも綺麗にしましょう！
これはノープロということで！！

2021-06-11 07:43 UTC, merged