change message improvement
Qithub-BOT/QiiCipher pull request #61
Opened 2021-06-13 02:03 UTC by yoshi389111

## 関連 issue

* issue #33 コマンドの引数が間違えていた場合のメッセージ改善
* issue #31 verifyがエラーになる？

## 対応内容

* 引数の入力ファイルの存在チェックを追加
* GitHub の公開鍵を取得できなかった場合にエラーを表示して終了する
* OpenSSL/OpenSSH のインストールチェックを追加
* 一部エラーメッセージの見直し（出力先を標準エラーにした。別コマンドのエラーメッセージを出力するようにした。など）
* 一部リファクタリング（ `$1` などを `"$1"` にした。多分問題ないが、念のため）

## （まだ）やっていないこと

* `archive` コマンドの tar と openssl のパイプしている処理は、tar でエラーが起きてもエラーメッセージがでない

```shell
if ! (tar -C "$(dirname "$INPUTFILE")" -cz "$(basename "$INPUTFILE")" | openssl enc -e -aes-256-cbc -salt -k "$PASSWORD" -out "${ARCHIVE_PATH}"); then
    echo >&2 "NG：ファイルを圧縮・暗号化できませんでした。"
    exit 1
fi
```

ワークファイルを経由してチェックしたほうがよいか…

2021-06-13 11:50 UTC, yoshi389111 commented
修正量が多くなってしまいましたが、時間のある時にでもレビューをお願いします

2021-06-14 04:02 UTC, KEINOS requested changes
すごーい！どんどん綺麗になっていってるー！ :tada:

一見多くみえますが、該当箇所に各々 `diff` でコメント付けただけで、大きく以下の 2 つが気になりました。

1. `openssl` 実行失敗時の標準エラー出力はそのまま出力させつつ `exit 1` させる（日本語以外のエラーの追跡情報として）
2.  テスト失敗時の英文メッセージが伝わりやすいように文言を修正

2021-06-14 04:04 UTC, KEINOS commented on tests/archive/not_installed_test.sh
> +}
あ、これは感想コメントです。（後日、自分の検索用）

2021-06-14 15:07 UTC, yoshi389111 commented on bin/check
> +fi
実はこのコマンドを実行すると、正常な場合にもstderrに出力がされるようです。
（以下の１つ目が正常、２つ目がエラー）

```
$ openssl rsa -in ~/.ssh/id_rsa.pem -text >/dev/null
writing RSA key
$ openssl rsa -in ~/.ssh/id_rsa.pub -text >/dev/null
unable to load Private Key
139998632383808:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
```

そのため、以下のように修正しました。
（標準エラーを `RESULT` に入れて、エラー時に出力する）

```shell
if ! RESULT="$(openssl rsa -in "${SECRETKEY}" -text 2>&1 >/dev/null)"; then
    echo >&2 "秘密鍵ファイル ${SECRETKEY} がサポートしていないフォーマットです。"
    echo >&2
    echo >&2 "Error(openssl)"
    echo >&2 "$RESULT"
    exit 1
fi
```

2021-06-14 15:07 UTC, yoshi389111 commented on bin/dec
> +fi
（上記同様に）修正しました

2021-06-14 15:07 UTC, yoshi389111 commented on bin/sign
> +fi
（上記同様に）修正しました

2021-06-14 15:07 UTC, yoshi389111 commented on tests/archive/not_installed_test.sh
> +    It 'not installed openssl'
修正しました

2021-06-14 15:08 UTC, yoshi389111 commented on tests/keygen/not_installed_test.sh
> +    It 'not installed openssh'
修正しました

2021-06-14 15:08 UTC, yoshi389111 commented on tests/sign/not_installed_test.sh
> +    It 'not installed openssh'
修正しました

2021-06-14 15:08 UTC, yoshi389111 commented on tests/verify/not_installed_test.sh
> +    It 'not installed openssl'
修正しました

2021-06-14 15:08 UTC, yoshi389111 commented on tests/verify/not_installed_test.sh
> +    It 'not installed openssh'
修正しました

2021-06-14 15:11 UTC, yoshi389111 commented on tests/archive/not_installed_test.sh
> +}
メモです。

`type` コマンドは組み込みコマンドのため、モックのやり方が少し違うようです。

* `Mock` コマンドではできないので、関数型モックを作る必要があります
* `When run` では組み込みコマンドのモックが有効にならないので、 `When run source` にする必要があります

2021-06-16 06:14 UTC, KEINOS commented on bin/check
> +fi
> 正常な場合にもstderrに出力がされる

ほんとだ！おいらの環境でも再現しました。なぜに `writing RSA key` がエラー出力なのだ！w
了解でございます！

2021-06-16 06:20 UTC, KEINOS approved these changes
どんどんガチガチになっていきますな！LGTM でございます！

![LooksガチToMe](https://user-images.githubusercontent.com/11840938/122167732-5330aa00-ceb6-11eb-81b8-dc3dbf3f35ec.png)

2021-06-16 06:24 UTC, merged